mutation add($addInput: AddUserInput!) {
    AddUser(AddUserInput: $addInput) {
        ...userResult
    }
}

mutation update($updateInput: UpdateUserInput!) {
    UpdateUser(UpdateUserInput: $updateInput) {
        ...userResult
    }
}

query getOne($getInput: QueryUserInput!) {
    GetUser(QueryUserInput: $getInput) {
        ...userResult
    }
}

query getAll($getAllInput: QueryUserInput) {
    QueryUsers(QueryUserInput: $getInput) {
        ...userResult
    }
}

fragment userResult on User {
    id
    firstName
    lastName
    email
    emailVerified
    phone
    role
    spaceId
    picture
    isActive
    createdAt
}
